### ISSUE TITLE
Why go through "all malicous labels + one possible subject"?

### ISSUE THREAD

**Issue by lesleychou** [purseclab/ATLAS#10]
Hi Alsaheel,

Sorry for bothering again. May I ask why do you need to append every subject to original malicious labels in [this for loop](https://github.com/purseclab/ATLAS/blob/64c94aa93c2cc7bda0bd25b278bd31ea4ae595ef/atlas.py#L380)? 

This step was taking a lot of time and computation. I wonder would only checking original malicious labels work here? Or is there something I missed in your "result_list" logic?

Thanks!

**Comment by cssaheel** [comment]
Hi Lesley,

in suggest_ground_truth() I aim at extracting all unique abstracted (i.e., tokenized) sequences, malicious or not.
so basically result_list returns with the unique sequences, that's why is not sufficient to only extract sequences from the malicious entities.
As you can see in the [Lines 394-399](https://github.com/purseclab/ATLAS/blob/64c94aa93c2cc7bda0bd25b278bd31ea4ae595ef/atlas.py#L394)
Before we assign a sequence as a malicious, we check if the tokenized sequence matches a malicious sequence, if not then we assign it as a non-malicious "0", otherwise we assign it as a malicious sequence "1". Thanks.
